run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-use-default: false

  # Keep signal high, noise low
  max-issues-per-linter: 0
  max-same-issues: 0

  # Ignore test-related false positives if needed
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck