services:
  postgres:
    image: postgres:16
    container_name: coldkeep_postgres
    environment:
      POSTGRES_USER: coldkeep
      POSTGRES_PASSWORD: coldkeep
      POSTGRES_DB: coldkeep
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema_postgres.sql:/docker-entrypoint-initdb.d/schema_postgres.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coldkeep_app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: coldkeep
      DB_PASSWORD: coldkeep
      DB_NAME: coldkeep
      DB_SSLMODE: disable
      COLDKEEP_STORAGE_DIR: /storage/containers
      COLDKEEP_CONTAINER_MAX_SIZE_MB: 64
    volumes:
      - ./storage:/storage

volumes:
  pgdata: