// Package engine defines the coldkeep engine boundary.
//
// The package owns typed operation requests and results, request-level
// validation, and behavior-preserving orchestration between headless callers
// and lower domain adapters. Lower packages execute injected storage, catalog,
// verification, maintenance, and recovery details without owning the public
// operation boundary.
//
// # Invariants
//
// Engine callers must not weaken these invariants:
//
//   - GC must never delete reachable data.
//   - Restore must never write outside the intended destination.
//   - Verify must fail closed on inconsistent catalog/storage state.
//   - Recovery must not legitimize corrupt mappings.
//   - Packed and legacy storage behavior must remain aligned.
//   - CLI parsing must not be the only place where correctness invariants live.
//   - Engine APIs must not weaken existing safety guarantees.
//
// # Dependency direction
//
//	cmd/coldkeep    may import internal/engine
//	internal/engine must not import cmd/coldkeep
//	domain packages must not import internal/engine
package engine

import "context"

// Engine is the behavior-preserving facade for coldkeep operations.
//
// All implementations must preserve existing CLI output, JSON output, exit
// codes, storage format, repository format, and schema behavior.
type Engine interface {
	// Stats returns repository statistics.
	Stats(ctx context.Context, req StatsRequest) (StatsResult, error)

	// Inspect returns metadata about a stored file.
	Inspect(ctx context.Context, req InspectRequest) (InspectResult, error)

	// Verify runs repository verification.
	Verify(ctx context.Context, req VerifyRequest) (VerifyResult, error)

	// SnapshotList returns snapshots matching the request filters.
	SnapshotList(ctx context.Context, req SnapshotListRequest) (SnapshotListResult, error)

	// SnapshotShow returns metadata and filtered files for a single snapshot.
	SnapshotShow(ctx context.Context, req SnapshotShowRequest) (SnapshotShowResult, error)

	// SnapshotStats returns aggregate or per-snapshot statistics.
	SnapshotStats(ctx context.Context, req SnapshotStatsRequest) (SnapshotStatsResult, error)

	// SnapshotDiff compares two snapshots and returns change entries.
	SnapshotDiff(ctx context.Context, req SnapshotDiffRequest) (SnapshotDiffResult, error)

	// SnapshotCreate creates a snapshot through the catalog-only snapshot domain.
	// Type is derived from request paths, omitted IDs are generated by the
	// engine, and the underlying mutation must remain atomic.
	SnapshotCreate(ctx context.Context, req SnapshotCreateRequest) (SnapshotCreateResult, error)

	// SnapshotDelete previews or executes a metadata-only snapshot deletion.
	// Preview is read-only and DB-only. Execute must be affected-row honest and
	// must not fabricate preview data.
	SnapshotDelete(ctx context.Context, req SnapshotDeleteRequest) (SnapshotDeleteResult, error)

	// SnapshotRestore restores snapshot-owned files through the engine boundary.
	// Destination mode and lexical root/path are explicit, repeated selectors are
	// preserved, restore may leave filesystem side effects before a later error,
	// and the engine must not perform GC or repair as part of restore.
	SnapshotRestore(ctx context.Context, req SnapshotRestoreRequest) (SnapshotRestoreResult, error)

	// GarbageCollect runs dry-run or live GC against the repository.
	// Safety invariant: GC must never delete reachable data.
	// Live GC is only supported on the PostgreSQL backend; dry-run is supported
	// on both backends.
	GarbageCollect(ctx context.Context, req GarbageCollectRequest) (GarbageCollectResult, error)

	// PlanGarbageCollection computes live-repository reachability and reclaim
	// impact without mutating database or storage state.
	PlanGarbageCollection(ctx context.Context, req GarbageCollectionPlanRequest) (GarbageCollectionPlanResult, error)

	// Store stores a file into the repository.
	// Safety invariant: Store must not create inconsistent catalog/storage state.
	// Active semantics are limited to single-file store.
	Store(ctx context.Context, req StoreRequest) (StoreResult, error)

	// StoreFolder recursively stores a directory with deterministic discovery,
	// bounded workers, aggregate results, and worker-writer finalization owned
	// below this engine boundary.
	StoreFolder(ctx context.Context, req StoreFolderRequest) (StoreFolderResult, error)

	// ListFiles returns completed current-state stored paths in path order.
	ListFiles(ctx context.Context, req ListFilesRequest) (ListFilesResult, error)

	// SearchFiles returns completed current-state paths matching typed filters.
	SearchFiles(ctx context.Context, req SearchFilesRequest) (SearchFilesResult, error)

	// GetConfiguration returns one validated repository write default.
	GetConfiguration(ctx context.Context, req GetConfigurationRequest) (GetConfigurationResult, error)

	// SetConfiguration validates and persists one repository write default.
	SetConfiguration(ctx context.Context, req SetConfigurationRequest) (SetConfigurationResult, error)

	// Repair validates, normalizes, deduplicates, and executes ordered catalog
	// integrity recomputations. Each target remains transactionally independent;
	// FailFast stops after the first execution failure.
	Repair(ctx context.Context, req RepairRequest) (RepairResult, error)
	// Recover executes the corrective repository recovery pass against the
	// injected database and configured container directory.
	Recover(ctx context.Context, req RecoverRequest) (RecoverResult, error)
	// Doctor executes recovery, schema validation, system verification, and
	// integrity audit in order, stopping on the first failed stage.
	Doctor(ctx context.Context, req DoctorRequest) (DoctorResult, error)

	// Remove removes logical files from the repository by logical file ID.
	// Safety invariant: Remove must never make valid data unrecoverable.
	// Method selection owns addressing semantics: this method is by-ID only.
	Remove(ctx context.Context, req RemoveRequest) (RemoveResult, error)

	// RemoveStoredPaths unlinks one or more current stored physical-path mappings.
	//
	// Method selection owns addressing semantics: this method is for current
	// physical_file.path mappings rather than logical file IDs.
	// Safety invariant: the operation must preserve logical-file identity,
	// file-chunk ownership, chunk live-reference counts, and payload storage.
	// Physical payload reclamation remains GC-owned.
	RemoveStoredPaths(ctx context.Context, req RemoveStoredPathsRequest) (RemoveStoredPathsResult, error)

	// Restore restores logical files by logical file ID.
	// Safety invariant: Restore must never write outside the intended destination.
	// Method selection owns addressing semantics: this method is by-ID only.
	Restore(ctx context.Context, req RestoreRequest) (RestoreResult, error)

	// RestoreStoredPath restores one current stored physical-path mapping.
	//
	// Method selection owns addressing semantics: this method restores exactly
	// one current physical_file.path mapping rather than a logical file ID.
	// Safety invariant: the operation must preserve logical identity,
	// physical mappings, snapshot state, and ref-count ownership. Storage may
	// temporarily pin chunks while reconstructing payloads.
	RestoreStoredPath(ctx context.Context, req RestoreStoredPathRequest) (RestoreStoredPathResult, error)
}
